name: Auto Pull Request

on:
  push:
    branches:
      - release/*
      - feature/*

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Automatically Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const branch = '${{ github.ref_name }}';
            core.info(branch);
            const release = branch.toLowerCase().startsWith('release/')
                          ? branch.substring('release/'.length)
                          : null;
            core.info(release);

            const release_list = [];

            const exec_options = {};
            exec_options.listeners = {
              stdline: (data) => {
                release_list.push(data);
              }
            };
            await exec.exec(
              'git',
              ['branch', '--list=release/*', '--sort=-refname', '--no-color'],
              exec_options
            );

            core.info(release_list);

            const latest_release = release_list[0];

            core.info(latest_release);

            const base_branch = release ? 'master' : latest_release;
            const create_draft = (!!release);

            const result = await github.rest.pulls.create({
              owner,
              repo,
              title:  branch,
              head:   branch,
              base:   base_branch,
              body:   'This pull request is auto-generated.',
              draft:  create_draft
            });
