name: Create Pull Request

on: push

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch Remote Branches
        run: |
          git fetch --all --depth=1
          git fetch origin ${{ github.event.repository.default_branch }}

      - name: Find Latest Release Branch
        id: latest-release-finder
        run: |
          export MASTER_BRANCH="${{ github.event.repository.default_branch }}"
          git                                       \
              for-each-ref                          \
              -format="%(refname:short)"            \
              --no-merged=origin/${MASTER_BRANCH}   \
              'refs/remotes/origin/release/'        \
          | sort --version-sort --reverse           \
          | ( cut -c 8-; echo "${MASTER_BRANCH}" )  \
          | ( echo -n "NAME=" ; head -n 1 )         \
          >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const head = '${{ github.ref_name }}';
            const is_release_pr = head.toLowerCase().startsWith('release/');
            const base = is_release_pr
                       ? '${{ github.event.repository.default_branch }}'
                       : '${{ steps.latest-release-finder.outputs.NAME }}';

            core.info('Attempting to create pull request.');
            core.info('Head branch is: ' + String(head));
            core.info('Base branch is: ' + String(base));

            try {
              const result = await github.rest.pulls.create({
                owner,
                repo,
                title:  head,
                head:   head,
                base:   base,
                draft:  is_release_pr
              });
            } catch(error) {
              if (error.message.toLowerCase().search('already exists') != -1) {
                throw error;
              }
              core.info('Such pull request already exists.');
            }
